---
title: "GWAS Report"
output:
  rmdformats::robobook:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: false
    highlight: tango
params:
  project: test-gwas
  regenie_merged: ../tests/output/test-gwas/05_regenie_merged/test-gwas.Y1.regenie.gz
  regenie_filename: test-gwas.Y1.regenie.gz
  phenotype: Y1
  phenotype_file: ../tests/input/phenotype.txt
  regenie_step1_log: ../tests/output/test-gwas/04_regenie_log/test-gwas.step1.log
  regenie_step2_log: ../tests/output/test-gwas/04_regenie_log/test-gwas.step2.log
---

```{r setup, include=FALSE}
library(qqman)
library(ggplot2)
library(skimr)
library(kableExtra)
```

## Summary

| Parameter     | Value                                      |
| ------------- |--------------------------------------------|
| Project       | `r params$project`                         |
| Phenotype       | `r params$phenotype`                     |
| Phenotype File      | `r params$phenotype_file`            |
| Regenie File      | `r params$regenie_filename`             |

## Regenie Log (Step 1)

```{r, echo=FALSE}
step1_log <- read.table(params$regenie_step1_log, 
                      sep ="\t", header = TRUE, dec =".")
kable(step1_log)
```

## Regenie Log (Step 2)

```{r, echo=FALSE}
step2_log <- read.table(params$regenie_step2_log, 
                      sep ="\t", header = TRUE, dec =".")
kable(step2_log)
```

## Phenotype Statistics

### Overview

```{r, echo=FALSE}
phenotypeTable <- read.table(params$phenotype_file, header=TRUE, sep=" ", dec = ".");
kable(skim(phenotypeTable) %>%
  dplyr::filter(skim_variable == params$phenotype)) %>%
  kableExtra::scroll_box(width = "100%")
```

### Histogram 
```{r, echo=FALSE}
ggplot(phenotypeTable, aes_string(x=params$phenotype)) + 
geom_histogram(color="black", fill="white",bins=30)
```

## Manhattan Plot

```{r, echo=FALSE}
regenieTable <- read.table(params$regenie_merged, header=TRUE, sep=" ", dec = ".");
pheno <- params$phenotype
manhattan(regenieTable, chr="CHROM", bp="GENPOS", snp="ID", p="LOG10P", logp= FALSE, cex = 0.3, col = c("blue4", "orange3"))
```

## QQ Plot

```{r, echo=FALSE}
qq(regenieTable$LOG10P)
```
